### ISSUE TITLE
Syntax error in code

### ISSUE THREAD

**Issue by rskumar** [quasoft/memstore#1]
https://github.com/quasoft/memstore/blob/72cbde23778087efc0d9af366d6f08ceacbf4705/memstore.go#L23

Due to wrong syntax at above line, `go get` fails.

**Comment by quasoft** [comment]
The reason is that this line of code uses a type alias, which is a new syntax feature introduced in [Go 1.9](https://blog.golang.org/go1.9). You are probably using an older version of Go.

Nevertheless, there is no benefit in using a type alias here and preventing use of the package in older version, so I reverted `valueType` to a regular type definition. That should fix issue #1.

Try go getting now.

**Comment by rskumar** [comment]
Oops, I never use type alias :) `go get` works now.
